### ISSUE TITLE
Panics found by fuzzing

### ISSUE THREAD

**Issue by WIZeaz** [jugglerchris/rust-html2text#93]
Hi, I am fuzzing this crate with afl.rs, and my fuzzer reports some panics. I will list the code snippets and panic information below. All code snippets are guaranteed to be run directly. I hope you can check whether these panics are bugs.

The first case is panicked at 'capacity overflow':
```rust
    let _local0 = html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator>::new(11787190863583748771, html2text::render::text_renderer::RichDecorator{});
    let mut _local1 = <html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator> as html2text::render::Renderer>::new_sub_renderer(&_local0, 11791448176899352125);
    let _ = <html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator> as html2text::render::Renderer>::add_horizontal_border(&mut _local1);
```
```
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:518:5
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: alloc::raw_vec::capacity_overflow
   3: alloc::raw_vec::RawVec<T,A>::allocate_in
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/raw_vec.rs:178:27
   4: alloc::raw_vec::RawVec<T,A>::with_capacity_in
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/raw_vec.rs:131:9
   5: alloc::vec::Vec<T,A>::with_capacity_in
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/vec/mod.rs:673:20
   6: <T as alloc::vec::spec_from_elem::SpecFromElem>::from_elem
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/vec/spec_from_elem.rs:15:21
   7: alloc::vec::from_elem
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/vec/mod.rs:2566:5
   8: html2text::render::text_renderer::BorderHoriz::new
             at ./src/render/text_renderer.rs:630:23
   9: <html2text::render::text_renderer::SubRenderer<D> as html2text::render::Renderer>::add_horizontal_border
             at ./src/render/text_renderer.rs:1010:41
  10: replay_html2text161::test_function161
             at ./fuzz_target/build/replay_html2text161/src/main.rs:36:13
  11: replay_html2text161::main
             at ./fuzz_target/build/replay_html2text161/src/main.rs:69:5
  12: core::ops::function::FnOnce::call_once
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The second case is panicked at 'attempt to subtract with overflow'
```rust
    let data=[60, 116, 97, 98, 108, 101, 62, 60, 116, 114, 62, 60, 116, 100, 62, 120, 105, 60, 48, 62, 0, 0, 0, 60, 116, 97, 98, 108, 101, 62, 58, 58, 58, 62, 58, 62, 62, 62, 58, 60, 112, 32, 32, 32, 32, 32, 32, 32, 71, 87, 85, 78, 16, 16, 62, 60, 15, 16, 16, 16, 16, 16, 16, 15, 38, 16, 16, 16, 15, 1, 16, 16, 16, 16, 16, 16, 162, 111, 107, 99, 91, 112, 57, 64, 94, 100, 60, 111, 108, 47, 62, 127, 60, 108, 73, 62, 125, 109, 121, 102, 99, 122, 110, 102, 114, 98, 60, 97, 32, 104, 114, 101, 102, 61, 98, 111, 103, 32, 105, 100, 61, 100, 62, 60, 111, 15, 15, 15, 15, 15, 15, 15, 39, 15, 15, 15, 106, 102, 59, 99, 32, 32, 32, 86, 102, 122, 110, 104, 93, 108, 71, 114, 117, 110, 100, 96, 121, 57, 60, 107, 116, 109, 247, 62, 60, 32, 60, 122, 98, 99, 98, 97, 32, 119, 127, 127, 62, 60, 112, 62, 121, 116, 60, 47, 116, 100, 62, 62, 60, 111, 98, 62, 123, 110, 109, 97, 101, 105, 119, 60, 112, 101, 101, 122, 102, 63, 120, 97, 62, 60, 101, 62, 60, 120, 109, 112, 32, 28, 52, 55, 50, 50, 49, 52, 185, 150, 99, 62, 255, 112, 76, 85, 60, 112, 62, 73, 100, 116, 116, 60, 75, 50, 73, 116, 120, 110, 127, 255, 118, 32, 42, 40, 49, 33, 112, 32, 36, 107, 57, 60, 5, 163, 62, 49, 55, 32, 33, 118, 99, 63, 60, 109, 107, 43, 119, 100, 62, 60, 104, 58, 101, 163, 163, 163, 163, 220, 220, 220, 220, 220, 220, 220, 220, 220, 220, 220, 220, 1, 107, 117, 107, 108, 44, 102, 58, 60, 116, 101, 97, 106, 98, 59, 60, 115, 109, 52, 58, 115, 98, 62, 232, 110, 114, 32, 60, 117, 93, 120, 112, 119, 111, 59, 98, 120, 61, 206, 19, 61, 206, 19, 59, 1, 110, 102, 60, 115, 0, 242, 64, 203, 8, 111, 50, 59, 121, 122, 32, 42, 35, 32, 37, 101, 120, 104, 121, 0, 242, 59, 63, 121, 231, 130, 130, 130, 170, 170, 1, 32, 0, 0, 0, 28, 134, 200, 90, 119, 48, 60, 111, 108, 118, 119, 116, 113, 59, 100, 60, 117, 43, 110, 99, 9, 216, 157, 137, 216, 157, 246, 167, 62, 60, 104, 61, 43, 28, 134, 200, 105, 119, 48, 60, 122, 110, 0, 242, 61, 61, 114, 231, 130, 130, 130, 170, 170, 170, 233, 222, 222, 162, 163, 163, 163, 163, 163, 163, 163, 85, 100, 116, 99, 61, 60, 163, 163, 163, 163, 163, 220, 220, 1, 109, 112, 105, 10, 59, 105, 220, 215, 10, 59, 122, 100, 100, 121, 97, 43, 43, 43, 102, 122, 100, 60, 62, 114, 116, 122, 115, 61, 60, 115, 101, 62, 215, 215, 215, 215, 215, 98, 59, 60, 109, 120, 57, 60, 97, 102, 113, 229, 43, 43, 43, 43, 43, 43, 43, 43, 43, 35, 43, 43, 101, 58, 60, 116, 98, 101, 107, 98, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 98, 99, 62, 60, 112, 102, 59, 124, 107, 111, 97, 98, 108, 118, 60, 116, 102, 101, 104, 97, 62, 60, 255, 127, 46, 60, 116, 101, 62, 60, 105, 102, 63, 116, 116, 60, 47, 116, 101, 62, 62, 60, 115, 98, 62, 123, 109, 108, 97, 100, 119, 118, 60, 111, 99, 97, 103, 99, 62, 60, 255, 127, 46, 60, 103, 99, 62, 60, 116, 98, 63, 60, 101, 62, 60, 109, 109, 231, 130, 130, 130, 213, 213, 213, 233, 222, 222, 59, 101, 103, 58, 60, 100, 111, 61, 65, 114, 104, 60, 47, 101, 109, 62, 60, 99, 99, 172, 97, 97, 58, 60, 119, 99, 64, 126, 118, 104, 100, 100, 107, 105, 60, 120, 98, 255, 255, 255, 0, 60, 255, 127, 46, 60, 113, 127];
    let _local0: html2text::RenderTree = html2text::parse(&data[..]);
    let _local1: html2text::RenderedText::<html2text::render::text_renderer::RichDecorator> = html2text::RenderTree::render(_local0, 1, html2text::render::text_renderer::RichDecorator{});
```
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/jjf/Fuzzing-Target-Generator/experiments/rust-html2text/src/lib.rs:1305:65
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: html2text::do_render_node::{{closure}}
             at ./src/lib.rs:1305:65
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /home/jjf/Fuzzing-Target-Generator/library/alloc/src/boxed.rs:2001:9
   5: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/ops/function.rs:262:13
   6: html2text::tree_map_reduce::{{closure}}
             at ./src/lib.rs:780:30
   7: core::option::Option<T>::map
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/option.rs:925:29
   8: html2text::tree_map_reduce
             at ./src/lib.rs:775:13
   9: html2text::render_tree_to_string
             at ./src/lib.rs:1128:5
  10: html2text::RenderTree::render
             at ./src/lib.rs:1542:23
  11: replay_html2text10::test_function10
             at ./fuzz_target/build/replay_html2text10/src/main.rs:39:95
  12: replay_html2text10::main
             at ./fuzz_target/build/replay_html2text10/src/main.rs:74:5
  13: core::ops::function::FnOnce::call_once
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This case is panicked at Option::unwrap:
```rust
    let mut _local0: html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::TrivialDecorator> = html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::TrivialDecorator>::new(18446744073709551615, html2text::render::text_renderer::TrivialDecorator{});
    let _local1_param0_helper1 = &mut (_local0);
    let _ = <html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::TrivialDecorator> as html2text::render::Renderer>::end_strikeout(_local1_param0_helper1);
```
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/jjf/Fuzzing-Target-Generator/experiments/rust-html2text/src/render/text_renderer.rs:1377:38
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::Option<T>::unwrap
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/option.rs:778:21
   4: <html2text::render::text_renderer::SubRenderer<D> as html2text::render::Renderer>::end_strikeout
             at ./src/render/text_renderer.rs:1377:9
   5: replay_html2text59::test_function59
             at ./fuzz_target/build/replay_html2text59/src/main.rs:34:13
   6: replay_html2text59::main
             at ./fuzz_target/build/replay_html2text59/src/main.rs:66:5
   7: core::ops::function::FnOnce::call_once
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

This case is panicked at 'Attempt to end a preformatted block which wasn't opened.'
```rust
    let _local0: html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator> = html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator>::new(14829735431805717965, html2text::render::text_renderer::RichDecorator{});
    let _local1_param0_helper1 = &(_local0);
    let mut _local1: html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator> = <html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator> as html2text::render::Renderer>::new_sub_renderer(_local1_param0_helper1, 14829735431805717810);
    let _local2_param0_helper1 = &mut (_local1);
    let _ = <html2text::render::text_renderer::SubRenderer::<html2text::render::text_renderer::RichDecorator> as html2text::render::Renderer>::end_pre(_local2_param0_helper1);
```
```
thread 'main' panicked at 'Attempt to end a preformatted block which wasn't opened.', /home/jjf/Fuzzing-Target-Generator/experiments/rust-html2text/src/render/text_renderer.rs:1027:13
stack backtrace:
   0: std::panicking::begin_panic
             at /home/jjf/Fuzzing-Target-Generator/library/std/src/panicking.rs:607:12
   1: <html2text::render::text_renderer::SubRenderer<D> as html2text::render::Renderer>::end_pre
             at ./src/render/text_renderer.rs:1027:13
   2: replay_html2text164::test_function164
             at ./fuzz_target/build/replay_html2text164/src/main.rs:36:13
   3: replay_html2text164::main
             at ./fuzz_target/build/replay_html2text164/src/main.rs:69:5
   4: core::ops::function::FnOnce::call_once
             at /home/jjf/Fuzzing-Target-Generator/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by jugglerchris** [comment]
I've had a further look.  The third and fourth ones are just misuses of the low-level rendering APIs (calling an `end_foo()` without having called a `start_foo()` first) so I don't think those are bugs.

That leaves the second one which I think could happen with some HTML input.  The width of 1 is also unreasonable, but nested lists etc. could narrow a reasonable width down.

**Comment by jugglerchris** [comment]
There isn't really a good way to assert on the first one - it's an allocation failure.  I could assert that the width is under some value, but picking a value is hard and would be a bit arbitrary.  For the third one replacing `.unwrap()` with `.expect()` with a helpful string would work I think.

**Comment by jugglerchris** [comment]
I started doing the simple changes but decided now was a good time to start using Result for error handling - it will always be possible to have some HTML which would need a wider output than requested, so now this will return an error rather than panicking.

**Comment by jugglerchris** [comment]
By the way, does afl.rs generate random programs calling Rust functions, or is that something you've added?

**Comment by WIZeaz** [comment]
> By the way, does afl.rs generate random programs calling Rust functions, or is that something you've added?

No, afl.rs does not provide this feature to generate random programs. Actually I am developing a tool to generate fuzz drivers for arbitrary crate, then I use afl.rs to do the fuzzing process.

**Comment by WIZeaz** [comment]
btw, I also find an interesting thing when I play with the second cases.
```rust
    let data=[60, 116, 97, 98, 108, 101, 62, 60, 116, 114, 62, 60, 116, 100, 62, 120, 105, 60, 48, 62, 0, 0, 0, 60, 116, 97, 98, 108, 101, 62, 58, 58, 58, 62, 58, 62, 62, 62, 58, 60, 112, 32, 32, 32, 32, 32, 32, 32, 71, 87, 85, 78, 16, 16, 62, 60, 15, 16, 16, 16, 16, 16, 16, 15, 38, 16, 16, 16, 15, 1, 16, 16, 16, 16, 16, 16, 162, 111, 107, 99, 91, 112, 57, 64, 94, 100, 60, 111, 108, 47, 62, 127, 60, 108, 73, 62, 125, 109, 121, 102, 99, 122, 110, 102, 114, 98, 60, 97, 32, 104, 114, 101, 102, 61, 98, 111, 103, 32, 105, 100, 61, 100, 62, 60, 111, 15, 15, 15, 15, 15, 15, 15, 39, 15, 15, 15, 106, 102, 59, 99, 32, 32, 32, 86, 102, 122, 110, 104, 93, 108, 71, 114, 117, 110, 100, 96, 121, 57, 60, 107, 116, 109, 247, 62, 60, 32, 60, 122, 98, 99, 98, 97, 32, 119, 127, 127, 62, 60, 112, 62, 121, 116, 60, 47, 116, 100, 62, 62, 60, 111, 98, 62, 123, 110, 109, 97, 101, 105, 119, 60, 112, 101, 101, 122, 102, 63, 120, 97, 62, 60, 101, 62, 60, 120, 109, 112, 32, 28, 52, 55, 50, 50, 49, 52, 185, 150, 99, 62, 255, 112, 76, 85, 60, 112, 62, 73, 100, 116, 116, 60, 75, 50, 73, 116, 120, 110, 127, 255, 118, 32, 42, 40, 49, 33, 112, 32, 36, 107, 57, 60, 5, 163, 62, 49, 55, 32, 33, 118, 99, 63, 60, 109, 107, 43, 119, 100, 62, 60, 104, 58, 101, 163, 163, 163, 163, 220, 220, 220, 220, 220, 220, 220, 220, 220, 220, 220, 220, 1, 107, 117, 107, 108, 44, 102, 58, 60, 116, 101, 97, 106, 98, 59, 60, 115, 109, 52, 58, 115, 98, 62, 232, 110, 114, 32, 60, 117, 93, 120, 112, 119, 111, 59, 98, 120, 61, 206, 19, 61, 206, 19, 59, 1, 110, 102, 60, 115, 0, 242, 64, 203, 8, 111, 50, 59, 121, 122, 32, 42, 35, 32, 37, 101, 120, 104, 121, 0, 242, 59, 63, 121, 231, 130, 130, 130, 170, 170, 1, 32, 0, 0, 0, 28, 134, 200, 90, 119, 48, 60, 111, 108, 118, 119, 116, 113, 59, 100, 60, 117, 43, 110, 99, 9, 216, 157, 137, 216, 157, 246, 167, 62, 60, 104, 61, 43, 28, 134, 200, 105, 119, 48, 60, 122, 110, 0, 242, 61, 61, 114, 231, 130, 130, 130, 170, 170, 170, 233, 222, 222, 162, 163, 163, 163, 163, 163, 163, 163, 85, 100, 116, 99, 61, 60, 163, 163, 163, 163, 163, 220, 220, 1, 109, 112, 105, 10, 59, 105, 220, 215, 10, 59, 122, 100, 100, 121, 97, 43, 43, 43, 102, 122, 100, 60, 62, 114, 116, 122, 115, 61, 60, 115, 101, 62, 215, 215, 215, 215, 215, 98, 59, 60, 109, 120, 57, 60, 97, 102, 113, 229, 43, 43, 43, 43, 43, 43, 43, 43, 43, 35, 43, 43, 101, 58, 60, 116, 98, 101, 107, 98, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 98, 99, 62, 60, 112, 102, 59, 124, 107, 111, 97, 98, 108, 118, 60, 116, 102, 101, 104, 97, 62, 60, 255, 127, 46, 60, 116, 101, 62, 60, 105, 102, 63, 116, 116, 60, 47, 116, 101, 62, 62, 60, 115, 98, 62, 123, 109, 108, 97, 100, 119, 118, 60, 111, 99, 97, 103, 99, 62, 60, 255, 127, 46, 60, 103, 99, 62, 60, 116, 98, 63, 60, 101, 62, 60, 109, 109, 231, 130, 130, 130, 213, 213, 213, 233, 222, 222, 59, 101, 103, 58, 60, 100, 111, 61, 65, 114, 104, 60, 47, 101, 109, 62, 60, 99, 99, 172, 97, 97, 58, 60, 119, 99, 64, 126, 118, 104, 100, 100, 107, 105, 60, 120, 98, 255, 255, 255, 0, 60, 255, 127, 46, 60, 113, 127];
    let _local0 = html2text::parse(&data[..]);
    let d1 = TrivialDecorator::new();
    let _local1 = html2text::RenderTree::render(_local0, 1, d1);
```
I replace the decorator to the `TrivialDecorator`, and it never ends in my computer. I think this is another problem?

**Comment by jugglerchris** [comment]
> No, afl.rs does not provide this feature to generate random programs. Actually I am developing a tool to generate fuzz drivers for arbitrary crate, then I use afl.rs to do the fuzzing process.

That sounds pretty nice!

**Comment by jugglerchris** [comment]
I've updated the branch to fix the above infinite loop.  It happened when there was a width of 1, and a 2 cell wide character.

**Comment by jugglerchris** [comment]
Merged.  I think everything here is fixed - if anything else comes up please open another issue.
